# configs/config.yaml
# -------------------
# プロジェクト全体設定ファイル
# 公式 SEPA / Minervini 最小値を採用し、公式の許容レンジをコメントで記載

fundamentals:
  enabled: true
  provider: "finnhub"            # 例: 'yahoo', 'alpha_vantage' など
  # api_key:  "${FINNHUB_KEY}" # ← ここに取得したキー
  eps_g_min: 20   # EPS Growth 最小 20 %
  rev_g_min: 20   # Sales Growth 最小 20 %        
live:
  capital: 1_000_000           # 運用予定元本 (JPY 換算)
  top_n: 5                     # 週次スクリーナー上位何銘柄まで取るか
  throttle_sec: 0.2            # 発注間隔(秒)

log_level: "INFO"              # グローバルログレベル

# ▼ 公式 SEPA 最小基準
sepa:
  universe: "us_largecap"      # または CSV/JSON ファイルパス

  # --- フィルタ条件 -------------------------------------------------------
  min_avg_volume: 1_000_000    # 20日平均出来高(株) 公式: **>= 1,000,000**
  min_price: 10                # 終値最低価格(USD) 公式: **>= 10**

  # --- リスク・エグジット・エントリ関連 ----------------------------------
  risk_pct: 0.002              # 口座リスク 0.2 % 公式レンジ: **0.2–1.0 %**
  stop_pct: 0.05               # ストップ幅 -5 % 公式レンジ: **5–8 %**
  tp1_pct: 0.10                # +10 % 到達で部分利確 公式レンジ: **10–20 %**
  tp1_size: 0.5                # 部分利確量 (50 %) 公式: **固定 50 %**
  trailing_ema: 10             # 残ポジは EMA10 割れで全決済 公式候補: **10EMA / 20EMA**

  # --- ポジション管理 -----------------------------------------------------
  max_positions: 8             # 最大同時保有銘柄数 公式レンジ: **8–12**

  # --- ブレイクアウト判定 -------------------------------------------------
  breakout_lookback: 65        # ピボット検索期間(日) ※公式明示なし、実装便宜上 13週=65日


