name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) ここで 3.11 をセット（これが最重要）
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 2) Poetry を pipx で入れる（3.11 環境上に入る）
      - name: Install Poetry
        run: pipx install poetry==2.1.4

      # 3) Poetry の設定（プロジェクト内 .venv を使う）
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry env use python   # setup-python の python を使わせる

      # 4) キャッシュ（任意だけど高速化に有効）
      - name: Cache poetry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      # 5) 依存インストール
      - name: Install deps
        run: poetry install --no-interaction --no-ansi

      # 6) テスト等
      - name: Run tests
        run: poetry run pytest -q
