name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

        - run: |
            pip install --upgrade pip
            pip install poetry
            poetry install --without dev
            poetry run pytest
              - run: |
                  poetry run black --check .
                  poetry run flake8 .
                  poetry run mypy sepa_trade
                  poetry run pylint sepa_trade
                  poetry run pytest --cov=sepa_trade --cov-report=xml --cov-report=html
                env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




